In [2]:
# Import libraries
import numpy as np
from numpy import random

### Creating Arrays

In [3]:
# 1D Array
arr = np.array([1,2,3,4,5])
print(arr)

# Practice for accessing elements
arr[1]
arr[:3]
arr[1:3]
arr[1] + arr[4]

[1 2 3 4 5]


np.int64(7)

In [4]:
# 2-D array
arr  = np.array([[1,2,3,4],[5,6,7,8],[11,12,13,18],[14,15,16,20]])
# print(arr)

# Practice for accessing elements
arr[1,1]
# arr[2,1:3]

np.int64(6)

In [5]:
# 3-D array
arr = np.array([[[1,2,3],[11,12,13]],[[22,23,24],[89,80,23]]])
arr

array([[[ 1,  2,  3],
        [11, 12, 13]],

       [[22, 23, 24],
        [89, 80, 23]]])

In [6]:
# Practice for accessing elements
arr[1,0,0:2]

array([22, 23])

### Creating Arrays with Initial Values

In [ ]:
# 2x3 matrix of zeros
zeros = np.zeros((2, 3))   

In [ ]:
# 3x3 matrix of ones
ones = np.ones((3, 3))     

In [ ]:
# 3x3 Identity matrix
identity = np.eye(3)       

In [ ]:
# Array of even numbers from 0 to 10
range_array = np.arange(0, 10, 2)  

### Random Arrays

In [ ]:
# 2x3 matrix with random values between 0 and 1
random_array = np.random.rand(2, 3)

In [ ]:
# 2x2 matrix with random integers between 0 and 9
int_random_array = np.random.randint(0, 10, (2, 2))

### Array Attributes (Important)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

### Array Indexing and Slicing

In [ ]:
# Indexing
arr = np.array([10, 22, 21, 24, 12])
print(arr[0])
print(arr[2])

In [ ]:
# Slicing
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[:3])

In [ ]:
# 2D Array Slicing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[1, 2])
print(matrix[0:2, 1:3])

### Mathematical Operations

In [39]:
# Element-wise Operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition, subtraction, multiplication, and division
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# Scalar Operations
arr = np.array([1, 2, 3])
print(arr * 2)
print(arr + 3)

In [ ]:
# Matrix Multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Dot profuct is basically very useful in matrix multiplicaition
result = np.dot(matrix1, matrix2)

### Statistical Operations

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Mean of array
print(np.mean(arr)) 

In [ ]:
# Median of array
print(np.median(arr))

In [ ]:
# Standard deviation
print(np.std(arr))

In [ ]:
# Sum of array
print(np.sum(arr))
# min of array
print(np.min(arr))
# max of array
print(np.max(arr))

### Sum and Product along an Axis

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
# Sum of each column: [5 7 9]
print(np.sum(matrix, axis=0))  

In [ ]:
# Product of each row: [6 120]
print(np.prod(matrix, axis=1))

### Reshaping and Resizing

In [ ]:
# 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
n_a = arr.reshape(2,6)
n_a

In [ ]:
# 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
n_a = arr.reshape(2,2,3)
n_a

#### Copy & View

In [7]:
# When we make changes in copy it would not effect the array
arr = np.array([1,2,3,4,5,6])
x = arr.copy()
arr[2] = 12
print(arr)
print(x)

[ 1  2 12  4  5  6]
[1 2 3 4 5 6]


In [8]:
#any changes made in view will effect the data but does not effect the orignal array
arr = np.array([1,2,3,4,5,6])
x = arr.view()
arr[3] = 13
print(arr)
print(x)

[ 1  2  3 13  5  6]
[ 1  2  3 13  5  6]


### Flattening

In [40]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened = matrix.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

### Concatenation and Splitting (NumPy Joining Array)

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1,arr2))
print(arr)

In [ ]:
# axis = 1
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1,arr2), axis=1)
print(arr)

In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concat = np.concatenate((arr1, arr2))
split = np.split(concat, 3)
print(split)

[array([1, 2]), array([3, 4]), array([5, 6])]


### Broadcasting

In [ ]:
# NumPy allows operations on arrays of different shapes as long as they are compatible. This feature is called broadcasting.
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
result = arr + scalar

### Linear Algebra Operations

In [ ]:
var = np.matrix([[1,2,3],[4,5,6]])
var1 = np.matrix([[1,2],[4,5],[4,5]])
var2 = np.array([[1,2,3],[4,5,6]])
var3 = np.array([[1,2,3],[4,5,6]])
print(var)
print(type(var))
print()
print(var1)
print(type(var1))
print(var.dot(var1))

In [ ]:
var = np.matrix([[1,2,3],[4,5,6]])
var1 = np.matrix([[1,2],[4,5],[4,5]])
print(var.dot(var1))

In [ ]:
# Transpose of matrix
print(var)
print()
x = np.transpose(var)
x1 = var.T # Another method for transpose
print(x1)
z = var.dot(x)
print(z)

In [ ]:
# Swapaxes
x = np.matrix([[1,2,3,4],[2,3,4,5],[5,6,7,8]])
x1 = np.matrix([[1,2,4],[2,3,4],[5,6,7]])
# print(np.swapaxes(x,0,1))
print(np.swapaxes(x1,0,1))

In [ ]:
# Inverse of matrix
x = np.matrix([[1,2,3],[2,3,4],[5,6,7]])
print(x)
print()
print(np.linalg.inv(x))

### Iterating Arrays

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
for i in arr:
    print(i, end=" ")

print("\n")

arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for i in arr1:
    for j in i:
        print(j, end=" ")

print("\n")
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in arr2:
    for j in i:
        for k in j:
            print(k, end=" ")

print("\n")

arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr3):
    print(x, end=" ")

print("\n")
for inx, x  in enumerate(arr1):
    print(inx," ",x)

1 2 3 4 5 6 7 8 9 10 11 12 

1 2 3 4 5 6 7 8 

1 2 3 4 5 6 7 8 9 10 11 12 

1 2 3 4 5 6 7 8 9 10 11 12 

0   [1 2 3 4]
1   [5 6 7 8]


### Random

In [16]:
from numpy import random

a = random.randint(10,20)
a
# random float
x = round(random.rand(), 2)
x

0.59

In [17]:
# random array
x = random.randint(50,100, size=5)
x

# Multi dimension array
x = random.randint(20,40, size=(2,3))
x
x = random.randint(20,40, size=(3,2,3))
x

array([[[39, 28, 31],
        [22, 32, 36]],

       [[27, 21, 30],
        [31, 27, 30]],

       [[20, 30, 34],
        [31, 23, 20]]], dtype=int32)

In [18]:
x = random.rand(5)
print(x)

[0.03939539 0.16970798 0.62753968 0.82885102 0.37053853]


## Practicing

In [19]:
w1, w2, w3 = 0.3, 0.2, 0.5
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [20]:
w1, w2, w3 = 0.3, 0.2, 0.5
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

weights = [w1,w2,w3]

def crop_yield(weight, region):
    result = 0
    for w,r in zip(weight,region):
        result += w*r
    return result

res = crop_yield(weights, kanto)
res1 = crop_yield(weights, unova)
print(res1)

74.9


In [21]:
weights = np.array([w1,w2,w3])
kanto = np.array([73, 67, 43])
weights
type(kanto)
type(weights)

np.dot(kanto,weights)
(kanto*weights).sum()

np.float64(56.8)

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1 * arr2
arr2.sum()

np.int64(15)

In [23]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))



In [24]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: total: 438 ms
Wall time: 1.01 s


833332333333500000

In [25]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
climate_data
weights.shape

(3,)

In [26]:
var = np.array([[1,2,3,4],[32,34,5,6]])
var1 = np.array([1,2,3])
print(var1)
print(var1.shape)

[1 2 3]
(3,)


In [27]:
v1 = np.array([1,2,3,4,5], ndmin=5)
print(v1)
print(v1.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


### Reshaping

In [28]:
var2 = np.array([1,2,3,4,5,3])
x = var2.reshape(2,3)
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 3]]
2


In [29]:
# Join Array
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])

var2 = np.concatenate((var,var1))
print(var2)


# In 2-D array we sumup as along axis
var3 = np.array([[1,2],[3,4]])
var4 = np.array([[5,6],[7,8]])
var5 = np.concatenate((var3,var4),axis = 1)
print(var5)

[1 2 3 4 5 6 7 8]
[[1 2 5 6]
 [3 4 7 8]]


### Search

In [30]:
var = np.array([1,2,3,4,5,6,7,8,9,1,2,2,3,4,5,3,3,3,2,5,5])
x = np.where( var >= 2 )
print

<function print>

In [36]:
v = np.arange(15,55)
print(v)
z = v[1:-1]
print(z)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [37]:
x = np.arange(10,22).reshape((3,4))
print(x)
for x in np.nditer(x):
    print(x, end=" ")

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
10 11 12 13 14 15 16 17 18 19 20 21 

In [38]:
x = np.linspace(5,50,10)
print(x)

y = np.arange(0,20)
print(y)
y[(y>=9) & (y<=15)] *= -1
print(y)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]
